Traceback (most recent call last):
  File "/home/river/nishka/fifo/new_main.py", line 409, in <module>
    main()
  File "/home/river/nishka/fifo/new_main.py", line 140, in main
    os.makedirs(args.snapshot_dir)
  File "/home/river/miniconda3/envs/pl/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/river/miniconda3/envs/pl/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/river/miniconda3/envs/pl/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/root/data1'